* React App in PureScript

This is a template repository that sets up a React starter app with a basic
PureScript component defined to get you started.

** Getting Started

*** Nix

Assumes you have Nix version 2.3 or installed.

Using Nix for your package manager merely requires you to run:

#+BEGIN_SRC text
./devshell
#+END_SRC

This enters you into the shell that contains all the dependencies you
need with the lowest amount of fuss.

In side that Nix shell:

#+BEGIN_SRC text
$ yarn install
#+END_SRC

You will be able to run all necessary commands for the various
activities during the course.

** Versions

If you are installing necessary dependencies via a method other than
Nix, please make sure your versions match the following or are above
without breaking changes in between.

PureScript (=purs=):
#+BEGIN_SRC text
$ purs --version
0.13.6
#+END_SRC

Spago (=spago=):
#+BEGIN_SRC text
$ spago version
0.13.1
#+END_SRC

NodeJS (=node=):
#+BEGIN_SRC text
$ node --version
v12.15.0
#+END_SRC

Yarn (=yarn=):
#+BEGIN_SRC text
$ yarn versions
1.22.0
#+END_SRC

